apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app5
  template:
    metadata:
      labels:
        app: hello-world-app5
    spec:
      containers:
        - name: hello-world-app5
          image: us-central1-docker.pkg.dev/end-to-end-project-438607/node-apps/hello-world-app5:999667019a1a9bdf776fa868ed4d86f5916d0e3a
          ports:
            - containerPort: 3004
